### ISSUE TITLE
Save-APIKey fails when the Master password length isn't divisible by 4

### ISSUE THREAD

**Issue by raesene** [darkoperator/Posh-Shodan#1]
Just setting up the module and when I try to use the Save-APIKey cmdlet I get an error setting it. 

```
ConvertFrom-SecureString : The specified key is not valid. Valid key length settings are either 128 bits, 192 bits, or
256 bits.
At C:\Program Files\WindowsPowerShell\Modules\Posh-Shodan\Posh-Shodan.psm1:34 char:47
+ ... SecureKeyString | ConvertFrom-SecureString -SecureKey $MasterPassword
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [ConvertFrom-SecureString], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.ConvertFromSecureStringCommand
```

Initially I thought it was a problem with the API Key length, but from experimenting with different password length it seems that the cmdlet works fine when the password length is divisible by 4 (e.g. 8, 12, 16 chars in length) and the error occurs when it's not.

**Comment by darkoperator** [comment]
Sorry about that, just pushed a fix, if you can download the latest from github and try again

**Comment by raesene** [comment]
Cool, 

Thanks for that, I've tried and confirmed that it works for me.
